# -*- coding: utf-8 -*-
"""exemplo0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i5tWQv3_rEchgZNpTFlhM_vLJz-H9R4b
"""

!pip install opencv-python
import cv2
from google.colab.patches import cv2_imshow

#O calculo é média ponderada dos canais de cor RGB(vermelho, verde e azul) de
#cada pixel da imagem original. O peso médio usado é o seguinte:L = 0.299 * R + 0.587 * G + 0.114 * B

img = cv2.imread("cores.jpg", 0)
cv2_imshow(img)