# -*- coding: utf-8 -*-
"""Rotação

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18BG7bTityPjUq0Gd23AM7VC_qZI4ljHI
"""

#Ivyna Alves
#Beatriz Leonara

#link da foto [https://www.google.com/url?sa=i&url=https%3A%2F%2Fvelozesclub.com.br%2Ftag%2Fvelozes-e-furiosos%2Fpage%2F9&psig=AOvVaw1_OodYp2LdAFXhB9hU4qnD&ust=1700610538181000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCLCdto7i04IDFQAAAAAdAAAAABAO]
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

img = cv2.imread('carro.jpg')
(h, w) = img.shape[:2]
center = (w/2, h/2)
angle = 45
scale = 1.0
rotation_matrix = cv2.getRotationMatrix2D(center, angle, scale)
rotated = cv2.warpAffine(img, rotation_matrix, (w, h))

cv2_imshow(img)
cv2.waitKey(0)
print()
cv2_imshow(rotated)
cv2.waitKey(0)
cv2.destroyAllWindows()